adding the codemagic workflows

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -18,13 +18,25 @@ workflows:
       - android/app/build/outputs/**/*.apk
     publishing:
       scripts:
+        - name: Load Firebase configuration
+          script: |
+            #!/usr/bin/env sh
+            set -e # exit on first failed command
+
+            echo $GOOGLE_APPLICATION_CREDENTIALS > $CM_BUILD_DIR/service-account.json
+            export GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/service-account.json
+        - name: Debugging Step
+          script: |
+            # Imprimir la ruta del archivo de credenciales
+            echo "Service Account JSON path: $CM_BUILD_DIR/service-account.json"
+            # Imprimir el contenido del archivo de credenciales (puedes quitar esto después de la depuración)
+            cat $CM_BUILD_DIR/service-account.json
+            # Verificar que la variable de entorno está configurada
+            echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
         - name: Distribute to Firebase App Distribution
           script: |
             # Instalar Firebase CLI
             curl -sL https://firebase.tools | bash
-            # Configurar las credenciales de la cuenta de servicio
-            echo $GOOGLE_APPLICATION_CREDENTIALS > $CM_BUILD_DIR/service-account.json
-            export GOOGLE_APPLICATION_CREDENTIALS=$CM_BUILD_DIR/service-account.json
             # Distribuir la app a Firebase App Distribution
             firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
               --app "1:761973486485:android:98f9b993fb008ebea07c9c" \
